<template><div><h2 id="x-chat-v3-模型介绍" tabindex="-1"><a class="header-anchor" href="#x-chat-v3-模型介绍"><span>X-Chat V3 模型介绍</span></a></h2>
<div class="custom-container tip"><p class="custom-container-title">更新时间</p>
<p>2024年7月6日20:00:00</p>
</div>
<p>X-Chat V3采用储值制，即用户预先充值一定金额，每次对话将根据对话字符数扣除相应的金额。</p>
<h3 id="模型介绍-仅展示x-chat-v3提供的模型" tabindex="-1"><a class="header-anchor" href="#模型介绍-仅展示x-chat-v3提供的模型"><span>模型介绍（仅展示X-Chat V3提供的模型）</span></a></h3>
<table>
<thead>
<tr>
<th>模型名称</th>
<th>输入价格（美元/百万token）</th>
<th>输出价格（美元/百万token）</th>
<th>备注</th>
</tr>
</thead>
<tbody>
<tr>
<td>gpt-4</td>
<td>3</td>
<td>10</td>
<td></td>
</tr>
<tr>
<td>gpt-4o</td>
<td>5</td>
<td>15</td>
<td></td>
</tr>
<tr>
<td>gpt-4o-lite</td>
<td>2</td>
<td>7</td>
<td>gpt-4o的轻量版本，价格更低，稳定性不高</td>
</tr>
<tr>
<td>gpt-4o-stable</td>
<td>8</td>
<td>20</td>
<td>gpt-4o的官方版本，稳定性最高，速度极快</td>
</tr>
<tr>
<td>gpt-4-turbo</td>
<td>10</td>
<td>30</td>
<td></td>
</tr>
<tr>
<td>claude-3-opus</td>
<td>5</td>
<td>10</td>
<td></td>
</tr>
<tr>
<td>claude-3.5-sonnet</td>
<td>3</td>
<td>15</td>
<td></td>
</tr>
<tr>
<td>claude-3-haiku</td>
<td>3</td>
<td>6</td>
<td></td>
</tr>
<tr>
<td>gemini-1.5-pro</td>
<td>5</td>
<td>10</td>
<td></td>
</tr>
<tr>
<td>llama-3-70b</td>
<td>5</td>
<td>15</td>
<td>对英文语境支持更好</td>
</tr>
<tr>
<td>mixtral-8x7b</td>
<td>5</td>
<td>15</td>
<td>对英文语境支持更好</td>
</tr>
<tr>
<td>通义千问</td>
<td>3</td>
<td>3</td>
<td></td>
</tr>
<tr>
<td>Qwen2-7B-Instruct</td>
<td>3</td>
<td>3</td>
<td>更强的通义千问模型</td>
</tr>
<tr>
<td>智谱GLM-4</td>
<td>3</td>
<td>3</td>
<td></td>
</tr>
<tr>
<td>glm-4-9b-chat</td>
<td>3</td>
<td>3</td>
<td>更强的glm4模型</td>
</tr>
<tr>
<td>moonshot-v1-32k</td>
<td>1</td>
<td>1</td>
<td></td>
</tr>
<tr>
<td>deepseek-chat/code</td>
<td>3</td>
<td>3</td>
<td></td>
</tr>
<tr>
<td>deepseek_chat/code</td>
<td>0.5</td>
<td>0.5</td>
<td>性价比最高的模型</td>
</tr>
<tr>
<td>minimax</td>
<td>1</td>
<td>1</td>
<td></td>
</tr>
<tr>
<td>step</td>
<td>3</td>
<td>3</td>
<td></td>
</tr>
<tr>
<td>Yi-1.5-9B-Chat-16K</td>
<td>3</td>
<td>3</td>
<td></td>
</tr>
<tr>
<td>tts-1</td>
<td>6</td>
<td>6</td>
<td>语音生成模型</td>
</tr>
<tr>
<td>tts-1-hd</td>
<td>6</td>
<td>6</td>
<td>语音生成模型</td>
</tr>
<tr>
<td>whisper-1</td>
<td>6</td>
<td>6</td>
<td>语音生成模型</td>
</tr>
</tbody>
</table>
<div class="custom-container tip"><p class="custom-container-title">价格说明</p>
<p>该模型价格仅供普通用户参考。对外提供商用服务的开发者、企业或组织、具有一定调用规模的个人用户可以获得更便宜的API价格，我们提供更专业的企业级API后台，便于进行审计及管理，如分配组织、为特定用户设置速率限制、额度限制，以及实时查看用户使用额度、设置违禁词过滤等。</p>
<p>X-Chat V3提供弱品牌标识版本，即不含明显的BASETEC品牌标识。同时也提供自定义更换你的品牌标识的服务，详情请咨询 <code v-pre>business@basetec.top</code> 。</p>
</div>
</div></template>


